---
on: [push, pull_request]
name: lint-test

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check .

  luacheck:
    name: luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: luajit-openresty
      - uses: leafo/gh-actions-luarocks@v6
      - run: luarocks install luacheck
      - run: luacheck .

  test:
    # Windows is not supported: terminal commands and tests use POSIX shell syntax
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        nvim-versions: ['v0.9.5', 'stable', 'nightly']
    name: test (${{ matrix.os }}, ${{ matrix.nvim-versions }})
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}

      - uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: luajit-openresty

      - uses: leafo/gh-actions-luarocks@v6

      - name: install vusted
        run: luarocks install vusted

      - name: run tests
        run: vusted ./test
